name: Build Document

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: nix
    steps:
      - name: Debug
        run: which node && node --version && which env && ls /usr/bin/

      - uses: https://gitea.com/actions/checkout@v6

      - name: Build document
        run: just build-nix

      - name: Upload PDF
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: document
          path: build-nix/main.pdf
